

lut = {
    'Language': (('', '', '', ''),  {
        'Boston Diagnostic Aphasia Exam-3': (('', 
                                              '', 
                                              '', 
                                              ''), {
            'Boston Naming Test': (('', 
                                    '', 
                                    '', 
                                    ''), {}),
            'Boston Naming (Short)': (('', 
                                       '', 
                                       '', 
                                       ''), {}),
            'Complex Ideation': (('', 
                                  '', 
                                  '', 
                                  ''), {}),
            'Commands': (('', 
                          '', 
                          '', 
                          ''), {}),
            'Repeating Phrases': (('', 
                                   '', 
                                   '', 
                                   ''), {}),
            'Cookie Theft': (('', 
                              '', 
                              '', 
                              ''), {}),
        }),
        'Multi-Lingual Aphasia  Exam-3' : (('', 
                                            '', 
                                            '', 
                                            ''), {
            'Tokens': (('', 
                        '', 
                        '', 
                        ''), {}),
            'Sentence Repetition': (('', 
                                     '', 
                                     '', 
                                     ''), {}),
            'Visual Naming': (('', 
                               '', 
                               '', 
                               ''), {}),
        }),
        'Right-Left Orientation' : (('', 
                                     '', 
                                     '', 
                                     ''), {}),
        'Peabody Picture Vocabulary Test-4' : (('', 
                                                '', 
                                                '', 
                                                ''), {}),
        'Pebody Picture vocabulary Test-3' : (('', 
                                               '', 
                                               '', 
                                               ''), {})
    }),
    'Academic Achievment'(('', '', '', ''), {
        'Weschler Test of Adult Reading' : (('',
                                             '',
                                             '',
                                             ''), {
            'Demographics Predicted Ss' : (('',
                                            '',
                                            '',
                                            ''), {}),
            'WAIS-II Predicted FSIQ' : (('',
                                         '',
                                         '',
                                         ''), {}),
        }
        'Wide Range Achievement Tests-4' : (('',
                                             '',
                                             '',
                                             ''), {
            'Word Reading': (('',
                              '',
                              '',
                              ''), {}),
            'Spelling': (('',
                          '',
                          '',
                          ''), {}),
            'Math': (('',
                      '',
                      '',
                      ''), {}),
            'Sentence Comprehension': (('',
                                        '',
                                        '',
                                        ''), {}),
        }
        'Wide Range Achievment Tests-3': (('',
                                           '',
                                           '',
                                           ''), {
            'Word Reading' : (('',
                               '',
                               '',
                               ''), {}),
            'Spelling' : (('',
                           '',
                           '',
                           ''), {}),
            'Math' : (('',
                       '',
                       '',
                       ''), {}),
}
