library(tidyverse)

# has_names is generated by looking at the extra variables from the redcap 
# template import csv file
has_names <- c(
  'wais',
  'wms',
  'hvlt',
  'cvlt',
  'bvmt',
  'bnt',
  'bdae',
  'wrat',
  'wjiii',
  'clock',
  'jlo',
  'sdmt',
  'pasat',
  'cpt3',
  'trails',
  'wcst',
  'letterfluency',
  'book',
  'pegs',
  'gripstrength',
  'gds',
  'bdi',
  'adfacs',
  'maq',
  'bai'
)

data_dictionary <- read_csv("./data/clinical_data_dictionary.csv")

data <- data_dictionary %>%
  select(variable = "Variable / Field Name",
         form = "Form Name",
         section_header = "Section Header",
         logic = "Branching Logic (Show field only if...)") %>%
  mutate(branch = str_match(logic, "\\[([[:alnum:]_]+)\\]")[, 2])

has_data <- data %>%
  filter(branch %in% has_names) %>%
  select(-logic)

write_delim(has_data, "../data/clinical_redcap_has_table.tsv", delim = "\t")
